[package]
name = "tinyaudio"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["android-examples"]

# Make sure the separate examples (i.e. for Android) will use the crate optimized.
[profile.dev.package."*"]
opt-level = 3

[target.'cfg(target_os = "android")'.dependencies]
aaudio = "0.1.1"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = {version = "0.3.9", features = ["minwindef", "winnt", "windef", "winuser", "dsound", "synchapi", "winbase" ] }